### ISSUE TITLE
Wikiart throwing error

### ISSUE THREAD

**Issue by teacoat** [ouhenio/StyleGAN3-CLIP-notebooks#16]
Hey there, thanks for this notebook! Using wikiart on the inversion notebook i'm getting this error: 

![image](https://user-images.githubusercontent.com/3913019/145599966-fefc4d67-639f-4957-8da9-fa76fd44079b.png)

**Comment by ouhenio** [comment]
Thanks for pointing this out! I believe it's fixed with PR #17.
